### PR TITLE
File RFeprocessing and Minor UI Fix

### PR DESCRIPTION
**Pull request by clackner-gpa**
Adressed:
XDA-5 in Landing Page
XDA-4 By Adding a Reprocess Endpoint in `FileProcessorNode` and updating Controller endpoints
Partially Addresses SC-41 by Adding Endpoint in XDA. SystemCenter will need to be updated after this is merged.

### CODE REVIEW

**Review by StephenCWills — APPROVED** [review]
@clackner-gpa I made quite a few changes so it might be good if you could review my work before merging.

**Comment by clackner-gpa** [comment]
Looks good to me. I noticed the `ReprocessFiles([FromBody] List<int> meterIDs, [FromBody] DateTime startDate, [FromBody] DateTime endDate)` endpoint wasn't updated. I don't know where that one is used. It's not the Processed Files Page in SystemCenter.

**Comment by StephenCWills** [comment]
Yeah, looks like that one still just puts analysis tasks into the `AnalysisTask` table. I believe that function is used by the `Advanced Reprocess` button on the `Data Files` page in dD Workbench.

**Comment by clackner-gpa** [comment]
Merging this. if we are right the last endoint is only used in the dDTools page which will be retired soon.

**Pull request merged**
