### PR TITLE
XDA-9 Convert FTT integration to data source for triggered emails

### PR DESCRIPTION
**Pull request by StephenCWills**
The main thing here is the `FTTDataSource` which produces a data set that includes the URL, query string, and image data from having queried FTT via the `FaultTraceToolInterop` CLI. Image data is stored in XML using base64. I replaced the `<ftt />` element with an `<embed />` element as a more generalized solution for embedding base64 image data in emails.

Companion to https://github.com/GridProtectionAlliance/SystemCenter/pull/310

### CODE REVIEW

**Comment by StephenCWills** [comment]
Here is an example data set produced by the FTT data source.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<data>
    <EventDetail>
      <Events>
        <Event id="1" />
      </Events>
      <Faults>
        <Fault num="1">
          <SummaryData>
            <MeterKey>FORTTEST</MeterKey>
            <MeterName>FORTTEST</MeterName>
            <StationKey>Fort</StationKey>
            <StationName>Fort</StationName>
            <LineKey>LKingsFort</LineKey>
            <LineName>Kings-Fort HP</LineName>
            <FaultType>AN</FaultType>
            <Inception>2012-04-27T00:48:11.6881333</Inception>
            <UTCInception>2012-04-27T00:48:11.6881333</UTCInception>
            <DurationCycles>3.499998000000000e+000</DurationCycles>
            <DurationMilliseconds>5.833329999999999e+001</DurationMilliseconds>
            <PrefaultCurrent>66.420728164</PrefaultCurrent>
            <PostfaultCurrent>21.0347339303</PostfaultCurrent>
            <ReactanceRatio>9.647537384067451e-001</ReactanceRatio>
            <FaultCurrent>6.147926653595621e+003</FaultCurrent>
            <Algorithm>Novosel</Algorithm>
            <SingleEndedDistance>6.2825103512</SingleEndedDistance>
            <EventStartTime>2012-04-27T00:48:11.3898</EventStartTime>
            <EventEndTime>2012-04-27T00:48:12.7697999</EventEndTime>
            <FileName>FortTest.dat</FileName>
            <ShortFileName>FortTest.dat</ShortFileName>
            <EventID>1</EventID>
            <FaultID>5</FaultID>
          </SummaryData>
        </Fault>
      </Faults>
      <Line>
        <Name>Kings-Fort HP</Name>
        <AssetKey>LKingsFort</AssetKey>
        <Length>21.152</Length>
        <Z1>16.9755767134</Z1>
        <A1>79.2013946225</A1>
        <R1>3.1805</R1>
        <X1>16.67497</X1>
        <Z0>54.615262752</Z0>
        <A0>73.8263729591</A0>
        <R0>15.21303</R0>
        <X0>52.4537</X0>
        <ZS>29.4914364363</ZS>
        <AS>75.8864048574</AS>
        <RS>7.1913433333</RS>
        <XS>28.6012133333</XS>
      </Line>
      <BreakerRestrike>N/A</BreakerRestrike>
      <PQDashboard>http://localhost/PQDashboard</PQDashboard>
    </EventDetail>
    <ftt>
      <fault num="1">
        <baseURL>http://localhost/dev/test/index.html?zoomToFault=n&amp;output=jpg</baseURL>
        <queryString>totalLine=1&amp;lineid_0=LKingsFort&amp;stationname_0=Fort&amp;distance_0=6.28251&amp;eventtime_0=2012-04-27T00:48:11.6881333</queryString>
        <fullURL>http://localhost:80/dev/test/index.html?zoomToFault=n&amp;output=jpg&amp;totalLine=1&amp;lineid_0=LKingsFort&amp;stationname_0=Fort&amp;distance_0=6.28251&amp;eventtime_0=2012-04-27T00:48:11.6881333</fullURL>
        <imageData>iVBORw0KGgoAAAANSUhEUgAAA+...</imageData>
      </fault>
    </ftt>
</data>
```

**Comment by StephenCWills** [comment]
Here is an example snippet to replace the `<ftt />` element we currently use in fault email templates.

```xml
<xsl:for-each select="/data/EventDetail/Faults/Fault">
    <xsl:variable name="faultID" select="@num" />
    <table class="center">
        <tr>
            <td><span style="font-weight: bold">Fault Trace</span></td>
        </tr>
        <tr>
            <td>
                <a>
                    <xsl:attribute name="href">http://graf/faulttracetool/?<xsl:value-of select="/data/ftt/fault[@num=$faultID]/queryString" /></xsl:attribute>
                    View in FTT
                </a>
            </td>
        </tr>
        <tr>
            <td>
                <embed>
                    <xsl:value-of select="/data/ftt/fault[@num=$faultID]/imageData" />
                </embed>
            </td>
        </tr>
    </table>
</xsl:for-each>
```

**Comment by StephenCWills** [comment]
Here is an example snippet to replace the `<ftt />` element we currently use in fault email templates.

```xml
<xsl:for-each select="/data/EventDetail/Faults/Fault">
    <xsl:variable name="faultID" select="@num" />
    <table class="center">
        <tr>
            <td><span style="font-weight: bold">Fault Trace</span></td>
        </tr>
        <tr>
            <td>
                <a>
                    <xsl:attribute name="href">http://fttserver/faulttracetool/?<xsl:value-of select="/data/ftt/fault[@num=$faultID]/queryString" /></xsl:attribute>
                    View in FTT
                </a>
            </td>
        </tr>
        <tr>
            <td>
                <embed>
                    <xsl:value-of select="/data/ftt/fault[@num=$faultID]/imageData" />
                </embed>
            </td>
        </tr>
    </table>
</xsl:for-each>
```

**Comment by StephenCWills** [comment]
Rebased - no changes were made.

**Review by clackner-gpa — APPROVED** [review]

**Pull request merged**
